Return `304 not modified` If Etag is match.
bearsunday/BEAR.Sunday pull request #122
Opened 2019-01-03 11:04 UTC by kalibora

See: https://github.com/bearsunday/BEAR.QueryRepository/pull/56#issuecomment-447738405

`If-None-Match` ヘッダを検証し、 `Etag` の値が一致していれば、ステータスコード 304 を返し、body は返さないようにしました。
ネットワーク帯域を節約することが目的です。

2019-01-03 17:21 UTC, koriym requested changes
`respondeIfETagMatch()`メソッドを`isModified()`の条件判断と`transferNotModified()'の304送出のメソッドに分けたらどうでしょうか？

2019-02-02 09:51 UTC, kalibora commented
@koriym 
すみません遅くなりましたが、 389e086 の変更みました。良いと思ったのですが、
テストが追従できていなかったので、オリジナルのものを継承するという形をとりました。

参考: https://github.com/auraphp/Aura.Web/blob/a1a4e45d14b21d40d716d341b78a050e1905cc05/tests/unit/src/FakeResponseSender.php#L24-L43

こういうやり方はありでしょうか？

2019-02-05 01:08 UTC, koriym approved these changes

2019-02-05 01:09 UTC, koriym commented
@kalibora はい、auraphpでもやってたと思います！

2019-02-05 01:57 UTC, merged

2019-02-05 04:01 UTC, koriym commented
https://github.com/bearsunday/BEAR.Sunday/pull/123/commits/a6360a91b59386bc0ab68a363078090387d00ec7

追加しました